### ISSUE TITLE
ncls slow

### ISSUE THREAD

**Issue by lmdu** [hunt-genes/ncls#1]
Hi,
Recently, We used ncls to find overlaps. We extracted start and end information for each feature from GTF files, and construct a NCLS object. However, ncls keeps running and stay at build_nested_list function for a long long time. Could you possibly help me?
Thank you in advance.

Ming

**Comment by endrebak** [comment]
Thanks for reporting. Could you send me the data and code you use? I’ll
debug it. I have used ncls a lot and it is super fast.

I have not changed the construction code, so if there is a bug I’ll be
surprised :)

**Comment by lmdu** [comment]
@endrebak 
Thank you for your reply. Our code is
`from ncls import NCLS
import numpy as np

starts = []
ends = []
ids = []
with open('data.txt') as fh:
	for line in fh:
		cols = line.strip().split()
		starts.append(int(cols[0]))
		ends.append(int(cols[1]))
		ids.append(int(cols[2]))

starts = np.array(starts, dtype=np.long)
ends = np.array(ends, dtype=np.long)
ids = np.array(ids, dtype=np.long)

ncls = NCLS(starts, ends, ids)

for i in ncls.find_overlap(76623690, 76624000):
	print(i)
`
I have attached out data file.
[data.txt](https://github.com/hunt-genes/ncls/files/2299359/data.txt)

**Comment by endrebak** [comment]
That is a bug, but I cannot help you with windows yet. NCLS should really be fast though, because as opposed to an interval tree, all it does is [qsort](https://www.tutorialspoint.com/c_standard_library/c_function_qsort.htm) an array two times, which is O(n*log n).

Thanks for getting back to me. I'll keep the issue open to remember to post a warning about Windows.

**Comment by lmdu** [comment]
@endrebak 
I am sorry for reporting this issue. It's not a bug of NCLS. It's a bug of Cython. I used the mingw64 and added `**-D MS_WIN64**` flag to gcc compiler to build NCLS. It worked very well.

**Comment by endrebak** [comment]
No problem. Thanks for reporting. When other people encounter the same issue they will find the solution here now.
