### ISSUE TITLE
Consider uploading wheel packages as well

### ISSUE THREAD

**Issue by Tarliton** [hunt-genes/ncls#10]
We need cython installed to install this library when it's source distributed.

If we have wheel packages we don't need cython previously installed to install it.

Thank you.

**Comment by endrebak** [comment]
I know, but it is a lot of work to create wheels for linux and macOS. There are wheels out for 0.0.41, will try to be more consistent :)

**Comment by endrebak** [comment]
Manylinux wheels for 35-7 uploaded to PyPI for 0.0.42 :) Script `build_wheels.sh` added to repo :)

**Comment by Tarliton** [comment]
Thank you very much for such a fast response. :)
