### ISSUE TITLE
Missing features

### ISSUE THREAD

**Issue by joachimwolff** [hunt-genes/ncls#9]
Hi,

I would like to replace IntervalTree with something faster and found your implementation. 

What I miss as features:

- a function that returns me all available intervals as list like this or as an iterator in python: 
`interval_list [(0, 5000, 0), (5000, 10000, 1), (10000, 15000, 2), (15000, 20000, 3), (20000, 25000, 4), (25000, 30000, 5), (30000, 35000, 6), (35000, 40000, 7), (40000, 45000, 8), (45000, 50000, 9)]`

- the general possibility to iterate over the intervals from python. 
- the possibility to call the 'len' function

Would it be possible for you to implement these features?

Would be really nice!

Best,

Joachim

**Comment by endrebak** [comment]
Thanks for creating an issue. I would love to do all that and more (a better str repr for example), and I will put it high on my TODO-list, but I am taking easter vacation now, so I will look at it the next week :)

**Comment by joachimwolff** [comment]
Thanks for your reply. 

No rush :)

**Comment by endrebak** [comment]
Fixed in `0.0.42`. Note that using `_ncls.intervals()` is silly slow and memory-consuming though. It is just a list of tuples of python ints.

**Comment by endrebak** [comment]
Did not mean to sound so negative above, btw XD.

**Comment by joachimwolff** [comment]
Thanks for the fast implementation. I will test it soon. 

Don't worry, I am a bit unsure if this piece of code which is using this functionally is really necessary. However, I think it is the best to replace it first, test it and than I can start to optimize.

**Comment by joachimwolff** [comment]
Is there any chance to get a support for deepcopy?

**Comment by endrebak** [comment]
Why do you need it? It is an immutable datastructure.

**Comment by joachimwolff** [comment]
The intervaltree is one of many class variables of a complex object which is mutable. In some raw cases we need to deepcopy the complex object to have the original values saved. 

If I am already asking for features :) :
  - how does it behave in cases the python object is overwritten? Is the memory freed immediately or only when the GC thinks it is time for it?

If you are interested: https://github.com/deeptools/HiCMatrix/blob/master/hicmatrix/HiCMatrix.py#L76

**Comment by endrebak** [comment]
Python has a very good Gc. In pyranges I just overwrite variables and it is
never wasteful.

And the NCLS is so quick to create that I do not store them, I just create
new ones when I need them 😂🙈

I __love__ deeptools, so feel free to ask questions. The more context I
have, the easier it would be to give good replies :) And if you want
help/pull requests/discuss something, feel free to ping me.

Ps. I am considering creating readers for deeptools file-formats in
pyranges :)

On Tuesday, April 16, 2019, Joachim Wolff <notifications@github.com>
